openapi: 3.0.2

info:
  version: 0.0.1
  title: Contact Api
  description: Contact Api for Open Web Technology Challenge

tags:
  - name: "Contact"
  - name: "Skill"

paths:

  /contact:
    post:
      tags:
        - "Contact"
      description: Create contact
      operationId: createContact
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Contact"
      responses:
        '201':
          description: Return new contact model
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Contact'

  /contact/{contactId}:
    get:
      tags:
        - "Contact"
      description: Get one contact
      operationId: getOneContact
      parameters:
        - in: path
          name: contactId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Return contact model
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Contact'
    put:
      tags:
        - "Contact"
      description: Update one contact
      operationId: updateContact
      parameters:
        - in: path
          name: contactId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Contact"
      responses:
        '200':
          description: Return updated contact model
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Contact'
    delete:
      tags:
        - "Contact"
      description: Delete one contact
      operationId: deleteContact
      parameters:
        - in: path
          name: contactId
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Contact is deleted

  /skill:
    post:
      tags:
        - "Skill"
      description: Create skill
      operationId: createSkill
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Skill"
      responses:
        '201':
          description: Return new skill model
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Skill'

  /skill/{skillId}:
    get:
      tags:
        - "Skill"
      description: Get one skill
      operationId: getOneSkill
      parameters:
        - in: path
          name: skillId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Return skill model
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Skill'
    put:
      tags:
        - "Skill"
      description: Update one skill
      operationId: updateSkill
      parameters:
        - in: path
          name: skillId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Skill"
      responses:
        '200':
          description: Return updated skill model
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Skill'
    delete:
      tags:
        - "Skill"
      description: Delete one skill
      operationId: deleteSkill
      parameters:
        - in: path
          name: skillId
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Skill is deleted

components:
  schemas:
    Skill:
      description: Skill model
      type: object
      properties:
        id:
          description: Id of the skill.
          type: string
          readOnly: true
        name:
          description: Skill name
          type: string
        level:
          description: Level of the skill
          type: string
          enum: ['LOW', 'INTERMEDIATE', 'HIGH']
    Contact:
      description: Contact model
      type: object
      properties:
        id:
          description: Id of the contact.
          type: string
          readOnly: true
        firstname:
          description: First name of the contact
          type: string
        lastname:
          description: Last name of the contact
          type: string
        fullname:
          description: Full name of the contact
          type: string
          readOnly: true
        address:
          description: Address of the contact
          type: string
        email:
          description: Email of the contact
          type: string
          format: email
        mobile:
          description: Mobile phone number of the contact
          type: string
