version: '3.8'
services:
  mongo:
    image: mongo:5.0.6
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo-js.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123qweASD
      MONGO_INITDB_DATABASE: contact
    restart: always
    ports:
      - 27017:27017

  backend:
    build:
      context: .
      dockerfile: backend.dockerfile
    restart: always
    environment:
      spring.data.mongodb.host: mongo
    depends_on:
      - mongo
    ports:
      - 8080:8080

  frontend:
    build:
      context: .
      dockerfile: frontend.dockerfile
    restart: always
    ports:
      - 80:80
